- name: Fetch address and token to add node
  become: true
  command: microk8s.add-node
  register: addnode

- name: Set add node address fact
  set_fact:
    addnode_address: "{{ addnode.stdout_lines | map('regex_search','^\\s*microk8s join?(.*)') | select('string') | list | first}}"

- name: addnode_address
  debug:
    msg: "{{ addnode_address }}"
